name: build-emonTH-firmware

on:
    push:
        tags:
            - '*'

jobs:
    build:
        name: Build with Arm toolchain
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install toolchain
              run: |
                sudo apt-get update
                sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi

            - name: Verify installation
              run: arm-none-eabi-gcc --version

            - name: Build firmware
              run: |
                make -j

            - name: Archive build artifacts
              uses: actions/upload-artifact@v4
              with:
                name: firmware-${{ github.ref_name }}
                path: bin/emonTH*.*

            - name: Create GitHub release and upload assets
              uses: softprops/action-gh-release@v2
              with:
                tag_name: ${{ github.ref_name }}
                name: ${{ github.ref_name }}
                files: |
                  bin/emonTH*.*
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
